/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FhStencilButton {
        "danger": boolean;
        "slot": string;
    }
}
declare global {
    interface HTMLFhStencilButtonElement extends Components.FhStencilButton, HTMLStencilElement {
    }
    var HTMLFhStencilButtonElement: {
        prototype: HTMLFhStencilButtonElement;
        new (): HTMLFhStencilButtonElement;
    };
    interface HTMLElementTagNameMap {
        "fh-stencil-button": HTMLFhStencilButtonElement;
    }
}
declare namespace LocalJSX {
    interface FhStencilButton {
        "danger"?: boolean;
        "slot"?: string;
    }
    interface IntrinsicElements {
        "fh-stencil-button": FhStencilButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fh-stencil-button": LocalJSX.FhStencilButton & JSXBase.HTMLAttributes<HTMLFhStencilButtonElement>;
        }
    }
}
