/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UcDrawer {
        "title": string;
    }
    interface UcOpenButton {
        "isOpen": boolean;
    }
}
declare global {
    interface HTMLUcDrawerElement extends Components.UcDrawer, HTMLStencilElement {
    }
    var HTMLUcDrawerElement: {
        prototype: HTMLUcDrawerElement;
        new (): HTMLUcDrawerElement;
    };
    interface HTMLUcOpenButtonElement extends Components.UcOpenButton, HTMLStencilElement {
    }
    var HTMLUcOpenButtonElement: {
        prototype: HTMLUcOpenButtonElement;
        new (): HTMLUcOpenButtonElement;
    };
    interface HTMLElementTagNameMap {
        "uc-drawer": HTMLUcDrawerElement;
        "uc-open-button": HTMLUcOpenButtonElement;
    }
}
declare namespace LocalJSX {
    interface UcDrawer {
        "title"?: string;
    }
    interface UcOpenButton {
        "isOpen"?: boolean;
    }
    interface IntrinsicElements {
        "uc-drawer": UcDrawer;
        "uc-open-button": UcOpenButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uc-drawer": LocalJSX.UcDrawer & JSXBase.HTMLAttributes<HTMLUcDrawerElement>;
            "uc-open-button": LocalJSX.UcOpenButton & JSXBase.HTMLAttributes<HTMLUcOpenButtonElement>;
        }
    }
}
